spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${SERVER_PORT:8080}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
frontend.origin=${FRONTEND_ORIGIN:http://localhost:3000}

# --- OBSERVABILITY & PROMETHEUS ---
# Expose the Prometheus metrics endpoint
management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.export.prometheus.enabled=true

# Add a tag so you can filter by "transaction-service" in Grafana
management.observations.key-values.application=transaction-service

# Enable histograms for P95/P99 latency calculations
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles-histogram.jdbc.connections.active=true

# Define specific SLA buckets for better accuracy
management.metrics.distribution.sla.http.server.requests=100ms,500ms,1s,2s

# Enable statistics for all Redis caches
spring.cache.redis.enable-statistics=true

# This ensures that all meter data (including caches) is sent to the /prometheus endpoint
management.metrics.export.prometheus.enabled=true
management.metrics.web.server.request.autotime.enabled=true
management.endpoint.metrics.enabled=true

# --- OPENTELEMETRY / DISTRIBUTED TRACING ---
spring.application.name=transaction-service
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://jaeger.banking.svc.cluster.local:4318/v1/traces

