apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: transaction-service-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: transaction-service # MUST match the label in your transaction-service-deployment.yaml
  namespaceSelector:
    matchNames:
      - banking
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s