apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-service-monitor
  namespace: banking
  labels:
    # CHANGED: This now matches your kubectl output
    release: monitoring 
spec:
  selector:
    matchLabels:
      app: user-service
  namespaceSelector:
    matchNames:
      - banking
  endpoints:
  - port: http
    path: /metrics
    interval: 15s