apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-service-monitor
  namespace: monitoring
  labels:
    release: kps                  # MUST match your kube-prometheus-stack release name
spec:
  namespaceSelector:
    any: true                     # or use matchNames: [banking] if you prefer
  selector:
    matchLabels:
      app: user-service           # matches the Service label
  endpoints:
    - port: http                  # matches Service port name "http"
      path: /metrics              # your FastAPI / Python metrics endpoint
      interval: 15s