apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - db-init-configmap.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - redis.yaml
  - kafka.yaml
  - user-service-deployment.yaml
  - user-service-svc.yaml
  - transaction-service.yaml
  - activity-service-deployment.yaml
  - frontend-deployment.yaml
  - gateway-services.yaml
